### PR TITLE
Add support for Illustrator

### PR DESCRIPTION
**Pull request by Roms1383**
Hi @rkamysz, I'll let you do the packaging and publishing because I don't know which workflow you use.

### CODE REVIEW

**Comment by Roms1383** [comment]
Also @rkamysz please note that for some reason, Adobe Illustrator opens correctly, but it doesn't close.
On photoshop it does :)

**Comment by Roms1383** [comment]
sample code used to test :
```ts
import { newAdobeApp, AdobeAppName, AdobeAppEvent, AdobeApp, BroadcastMessage } from 'adobe-node'

const sleep = (duration: number) => new Promise(resolve => { setTimeout(resolve, duration) })

const run = async () => {
  try {
    const app : AdobeApp = newAdobeApp({
      app: {
        name: AdobeAppName.Illustrator,
        path: '/Applications/Adobe Illustrator CC 2019/Adobe Illustrator.app/Contents/MacOS/Adobe Illustrator',
        adobeScriptsPath: '/Applications/Adobe Illustrator CC 2019/Presets.localized/en_US/Scripts',
      },
      host: 'localhost',
      port: 5000,
      jsPath: '.'
    })
    .on(AdobeAppEvent.OpenApp, () => {
      console.log(`The Adobe App is open`)
    })
    .on(AdobeAppEvent.CloseApp, () => {
        console.log(`The Adobe App has been closed`);
    })
  
    app.init()
    await app.open()
    await sleep(2000)
    await app.close()
    app.dispose()
  } catch (e) { console.error(e) }
}
run()
```

**Comment by Roms1383** [comment]
Apparently though, when I kill the process in the terminal with `^+c`, Illustrator closes together.

**Comment by Roms1383** [comment]
There's something really weird too : when I `git clone` your repo locally and try to hack around, the Adobe app get opened correctly but the event listener never get triggered.
But when I install your library as a dependency, it get triggered correctly.
How do you package your files for npm publish ?
Have you ever had this issue yourself ?

**Comment by rkamysz** [comment]
Hi @Roms1383, thanks, I'll add this change. I will also include the rest of Adobe applications.
As for your problem with Illustrator, I don't know why this happens, you can try a simple script that opens and closes the process (`execFile` and` kill`). If I find some time, I'll install the trial version.

Secondly, about using this repository locally. You probably don't have "adobe-broadcast" installed. Check `package.json`, there is one` bin`, create an alias for it.

**Review by rkamysz — APPROVED** [review]

**Comment by rkamysz** [comment]
@1.1.3 Thanks!

**Pull request merged**
